name: CI Pipline

on: 
  push:
    branches:
      -master
  pull_request:
    branches: 
      -master 

jobs: 
  tests:
    runs-on: ubuntu-latest

    steps: 
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Install dependencies
        uses: actions/setup-node@v3
        with: 
          node-version: '18' # use a Node.js version compatible with your react app 

      # Step 3: Install Depenedencies
      - name: Install Depenedencies
        run: npm install 

      # Step 4: Run Tests
      - name: Run Tests
        run: npm test -- --watchAll=false 
